GET http://localhost:3000/protected
Authorization: Bearer your-generated-token
###

POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "abcd",
  "password": "demo"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "Kyle",
  "password": "demo"
}